language: perl
sudo: required
dist: xenial

services:
  - docker

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

branches:
  except:
    - /^debian\/\d/

notifications:
  email:
      - team@openas.org

deploy:
  provider: launchpad
  slug: "~open-as-team/open-as-cgw/master"
  oauth_token: "$LP_OAUTH_TOKEN"
  oauth_token_secret: "$LP_OAUTH_SECRET"
